#dubbo conf
dubbo:
  application:
    name: b2cmall-manager-web
  registry:
    address: zookeeper://192.168.152.129:2181
#picture upload conf
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
#tomcat conf
server:
  port: 8081
